"""add_share_id

Revision ID: 36cbaf3fa4fc
Revises: 52691b452401
Create Date: 2026-06-05 16:43:23.875001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36cbaf3fa4fc'
down_revision: Union[str, Sequence[str], None] = '52691b452401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_jobs', sa.Column('share_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_media_jobs_share_id'), 'media_jobs', ['share_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_jobs_share_id'), table_name='media_jobs')
    op.drop_column('media_jobs', 'share_id')
    # ### end Alembic commands ###
