"""initial

Revision ID: 52691b452401
Revises: 
Create Date: 2026-06-04 23:36:17.207877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52691b452401'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_uuid', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('cvd_type', sa.String(), nullable=True),
    sa.Column('is_diagnosed', sa.String(), nullable=True),
    sa.Column('prior_tool_use', sa.String(), nullable=True),
    sa.Column('color_glasses_frequency', sa.String(), nullable=True),
    sa.Column('web_app_comfort', sa.String(), nullable=True),
    sa.Column('device_use_frequency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_participants_id'), 'research_participants', ['id'], unique=False)
    op.create_index(op.f('ix_research_participants_participant_uuid'), 'research_participants', ['participant_uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('media_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_saved_permanently', sa.Boolean(), nullable=True),
    sa.Column('s3_key_original', sa.String(), nullable=True),
    sa.Column('s3_key_processed', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_jobs_id'), 'media_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_media_jobs_job_id'), 'media_jobs', ['job_id'], unique=True)
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('sus_q1', sa.Integer(), nullable=True),
    sa.Column('sus_q2', sa.Integer(), nullable=True),
    sa.Column('sus_q3', sa.Integer(), nullable=True),
    sa.Column('sus_q4', sa.Integer(), nullable=True),
    sa.Column('sus_q5', sa.Integer(), nullable=True),
    sa.Column('sus_q6', sa.Integer(), nullable=True),
    sa.Column('sus_q7', sa.Integer(), nullable=True),
    sa.Column('sus_q8', sa.Integer(), nullable=True),
    sa.Column('sus_q9', sa.Integer(), nullable=True),
    sa.Column('sus_q10', sa.Integer(), nullable=True),
    sa.Column('nasa_mental', sa.Integer(), nullable=True),
    sa.Column('nasa_physical', sa.Integer(), nullable=True),
    sa.Column('nasa_temporal', sa.Integer(), nullable=True),
    sa.Column('nasa_performance', sa.Integer(), nullable=True),
    sa.Column('nasa_effort', sa.Integer(), nullable=True),
    sa.Column('nasa_frustration', sa.Integer(), nullable=True),
    sa.Column('comfort_q1', sa.Integer(), nullable=True),
    sa.Column('comfort_q2', sa.Integer(), nullable=True),
    sa.Column('comfort_q3', sa.Integer(), nullable=True),
    sa.Column('comfort_q4', sa.Integer(), nullable=True),
    sa.Column('comfort_q5', sa.Integer(), nullable=True),
    sa.Column('interview_visual_transitions', sa.String(), nullable=True),
    sa.Column('interview_naturalness', sa.String(), nullable=True),
    sa.Column('interview_wizard_onboarding', sa.String(), nullable=True),
    sa.Column('interview_frustrating_aspects', sa.String(), nullable=True),
    sa.Column('interview_helpful_aspects', sa.String(), nullable=True),
    sa.Column('interview_open_feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['research_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    op.create_table('vision_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cvd_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('contrast_multiplier', sa.Float(), nullable=True),
    sa.Column('saturation_multiplier', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vision_profiles_id'), 'vision_profiles', ['id'], unique=False)
    op.create_table('vision_test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('task1_original_time', sa.Float(), nullable=True),
    sa.Column('task1_original_correct', sa.Boolean(), nullable=True),
    sa.Column('task1_corrected_time', sa.Float(), nullable=True),
    sa.Column('task1_corrected_correct', sa.Boolean(), nullable=True),
    sa.Column('task2_original_time', sa.Float(), nullable=True),
    sa.Column('task2_original_correct', sa.Boolean(), nullable=True),
    sa.Column('task2_corrected_time', sa.Float(), nullable=True),
    sa.Column('task2_corrected_correct', sa.Boolean(), nullable=True),
    sa.Column('task3_original_time', sa.Float(), nullable=True),
    sa.Column('task3_original_correct', sa.Boolean(), nullable=True),
    sa.Column('task3_corrected_time', sa.Float(), nullable=True),
    sa.Column('task3_corrected_correct', sa.Boolean(), nullable=True),
    sa.Column('video_original_time', sa.Float(), nullable=True),
    sa.Column('video_original_clicks', sa.Integer(), nullable=True),
    sa.Column('video_original_accuracy', sa.Float(), nullable=True),
    sa.Column('video_corrected_time', sa.Float(), nullable=True),
    sa.Column('video_corrected_clicks', sa.Integer(), nullable=True),
    sa.Column('video_corrected_accuracy', sa.Float(), nullable=True),
    sa.Column('document_original_time', sa.Float(), nullable=True),
    sa.Column('document_original_correct', sa.Boolean(), nullable=True),
    sa.Column('document_corrected_time', sa.Float(), nullable=True),
    sa.Column('document_corrected_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['research_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_test_sessions_id'), 'vision_test_sessions', ['id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['media_job_id'], ['media_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_job_id')
    )
    op.create_index(op.f('ix_compliance_reports_id'), 'compliance_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_reports_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_vision_test_sessions_id'), table_name='vision_test_sessions')
    op.drop_table('vision_test_sessions')
    op.drop_index(op.f('ix_vision_profiles_id'), table_name='vision_profiles')
    op.drop_table('vision_profiles')
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_media_jobs_job_id'), table_name='media_jobs')
    op.drop_index(op.f('ix_media_jobs_id'), table_name='media_jobs')
    op.drop_table('media_jobs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_research_participants_participant_uuid'), table_name='research_participants')
    op.drop_index(op.f('ix_research_participants_id'), table_name='research_participants')
    op.drop_table('research_participants')
    # ### end Alembic commands ###
