"""add task6

Revision ID: a6fdf9e28dc5
Revises: 52691b452401
Create Date: 2026-06-19 08:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = 'a6fdf9e28dc5'
down_revision: Union[str, Sequence[str], None] = '66d03520679a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vision_test_sessions', sa.Column('task6_original_time', sa.Float(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('task6_original_correct', sa.Boolean(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('task6_corrected_time', sa.Float(), nullable=True))
    op.add_column('vision_test_sessions', sa.Column('task6_corrected_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vision_test_sessions', 'task6_original_time')
    op.drop_column('vision_test_sessions', 'task6_original_correct')
    op.drop_column('vision_test_sessions', 'task6_corrected_time')
    op.drop_column('vision_test_sessions', 'task6_corrected_correct')
    # ### end Alembic commands ###
