"""add selected_mode

Revision ID: e8fdf9e28dc6
Revises: a6fdf9e28dc5
Create Date: 2026-06-19 12:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fdf9e28dc6'
down_revision: Union[str, Sequence[str], None] = 'a6fdf9e28dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_participants', sa.Column('selected_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_participants', 'selected_mode')
    # ### end Alembic commands ###
