"""Add cvd_type and severity to media_jobs

Revision ID: f130000867d7
Revises: f28ade34eaed
Create Date: 2026-06-26 22:04:03.897211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f130000867d7'
down_revision: Union[str, Sequence[str], None] = 'f28ade34eaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_jobs', sa.Column('cvd_type', sa.String(), nullable=True))
    op.add_column('media_jobs', sa.Column('severity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_jobs', 'severity')
    op.drop_column('media_jobs', 'cvd_type')
    # ### end Alembic commands ###
