"""Add telemetry fields

Revision ID: f28ade34eaed
Revises: e8fdf9e28dc6
Create Date: 2026-06-26 18:54:22.404531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28ade34eaed'
down_revision: Union[str, Sequence[str], None] = 'e8fdf9e28dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_reports', sa.Column('original_delta_e', sa.Float(), nullable=True))
    op.add_column('compliance_reports', sa.Column('remapped_delta_e', sa.Float(), nullable=True))
    op.add_column('compliance_reports', sa.Column('luminance_drift', sa.Float(), nullable=True))
    op.add_column('compliance_reports', sa.Column('audit_accuracy_verified', sa.Boolean(), nullable=True))
    op.add_column('media_jobs', sa.Column('processing_mode', sa.String(), nullable=True))
    op.add_column('media_jobs', sa.Column('processing_duration_ms', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('upload_latency_ms', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('pdf_page_count', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('pdf_vector_complexity', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('original_size_bytes', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('processed_size_bytes', sa.Integer(), nullable=True))
    op.add_column('media_jobs', sa.Column('video_fps', sa.Float(), nullable=True))
    op.add_column('vision_profiles', sa.Column('calibration_steps_taken', sa.Integer(), nullable=True))
    op.add_column('vision_profiles', sa.Column('calibration_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vision_profiles', 'calibration_method')
    op.drop_column('vision_profiles', 'calibration_steps_taken')
    op.drop_column('media_jobs', 'video_fps')
    op.drop_column('media_jobs', 'processed_size_bytes')
    op.drop_column('media_jobs', 'original_size_bytes')
    op.drop_column('media_jobs', 'pdf_vector_complexity')
    op.drop_column('media_jobs', 'pdf_page_count')
    op.drop_column('media_jobs', 'upload_latency_ms')
    op.drop_column('media_jobs', 'processing_duration_ms')
    op.drop_column('media_jobs', 'processing_mode')
    op.drop_column('compliance_reports', 'audit_accuracy_verified')
    op.drop_column('compliance_reports', 'luminance_drift')
    op.drop_column('compliance_reports', 'remapped_delta_e')
    op.drop_column('compliance_reports', 'original_delta_e')
    # ### end Alembic commands ###
